# Generated by Django 5.1.7 on 2025-05-19 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_adminprofile_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid username. This value may contain only letters, numbers, spaces, and @/./+/-/_ characters.', regex='^[\\w.@+\\- ]+$')]),
        ),
    ]
